/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTokenManager.java */
package Test;
import java.io.*;
import java.util.Scanner;

/** Token Manager. */
public class MyNewGrammarTokenManager implements MyNewGrammarConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 196;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0xf7ffff7e00000000L & l) != 0L)
                  {
                     if (kind > 32)
                        kind = 32;
                  }
                  if (curChar == 60)
                     jjAddStates(0, 26);
                  break;
               case 1:
                  if (curChar == 60)
                     jjAddStates(0, 26);
                  break;
               case 2:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(3, 10);
                  break;
               case 3:
                  if ((0xa7ffff7e00000000L & l) != 0L)
                     jjCheckNAddTwoStates(3, 10);
                  break;
               case 4:
                  if (curChar == 62 && kind > 5)
                     kind = 5;
                  break;
               case 9:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 16:
                  if ((0x4ffffffe00000000L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 20:
                  if (curChar != 62)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 21:
                  if ((0xffffffe00000000L & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 26:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(28, 35);
                  break;
               case 28:
                  if ((0xa7ffff7e00000000L & l) != 0L)
                     jjCheckNAddTwoStates(28, 35);
                  break;
               case 29:
                  if (curChar == 62 && kind > 8)
                     kind = 8;
                  break;
               case 34:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 41:
                  if ((0x7ffffffe00000000L & l) != 0L && kind > 9)
                     kind = 9;
                  break;
               case 45:
                  if (curChar != 62)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 46:
                  if ((0xfffffffe00000000L & l) != 0L && kind > 10)
                     kind = 10;
                  break;
               case 51:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 53:
                  if ((0xa7ffff7e00000000L & l) != 0L)
                     jjAddStates(27, 28);
                  break;
               case 54:
                  if (curChar == 62 && kind > 11)
                     kind = 11;
                  break;
               case 58:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(59, 66);
                  break;
               case 59:
                  if ((0xa7ffff7e00000000L & l) != 0L)
                     jjCheckNAddTwoStates(59, 66);
                  break;
               case 60:
                  if (curChar == 62 && kind > 12)
                     kind = 12;
                  break;
               case 65:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 72:
                  if ((0xfffffffe00000000L & l) != 0L && kind > 13)
                     kind = 13;
                  break;
               case 76:
                  if (curChar != 62)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0xfffffffe00000000L & l) != 0L && kind > 14)
                     kind = 14;
                  break;
               case 82:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(84, 88);
                  break;
               case 84:
                  if ((0xa7ffff7e00000000L & l) != 0L)
                     jjCheckNAddTwoStates(84, 88);
                  break;
               case 85:
                  if (curChar == 62 && kind > 15)
                     kind = 15;
                  break;
               case 87:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 91:
                  if ((0xa7ffff7e00000000L & l) != 0L)
                     jjAddStates(29, 30);
                  break;
               case 92:
                  if (curChar == 62 && kind > 16)
                     kind = 16;
                  break;
               case 93:
                  if (curChar != 62)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 94:
                  if ((0xfffffffe00000000L & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 96:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 98:
                  if ((0xfffffffe00000000L & l) != 0L)
                     jjAddStates(31, 32);
                  break;
               case 99:
                  if (curChar == 62 && kind > 18)
                     kind = 18;
                  break;
               case 104:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 110:
                  if ((0xa7ffff7e00000000L & l) != 0L)
                     jjAddStates(33, 34);
                  break;
               case 111:
                  if (curChar == 62 && kind > 19)
                     kind = 19;
                  break;
               case 114:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(115, 121);
                  break;
               case 115:
                  if ((0xa7ffff7e00000000L & l) != 0L)
                     jjCheckNAddTwoStates(115, 121);
                  break;
               case 116:
                  if (curChar == 62 && kind > 20)
                     kind = 20;
                  break;
               case 120:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 126:
                  if ((0xa7ffff7e00000000L & l) != 0L)
                     jjAddStates(35, 36);
                  break;
               case 127:
                  if (curChar == 62 && kind > 21)
                     kind = 21;
                  break;
               case 130:
                  if (curChar != 62)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 131:
                  if ((0xfffffffe00000000L & l) != 0L && kind > 22)
                     kind = 22;
                  break;
               case 135:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 137:
                  if ((0xfffffffe00000000L & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 142:
                  if (curChar != 62)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 143:
                  if ((0xfffffffe00000000L & l) != 0L && kind > 24)
                     kind = 24;
                  break;
               case 149:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 151:
                  if ((0xfffffffe00000000L & l) != 0L && kind > 25)
                     kind = 25;
                  break;
               case 153:
                  if (curChar != 62)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 154:
                  if ((0xfffffffe00000000L & l) != 0L && kind > 26)
                     kind = 26;
                  break;
               case 157:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 158:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(159, 164);
                  break;
               case 159:
                  if ((0xa7ffff7e00000000L & l) != 0L)
                     jjCheckNAddTwoStates(159, 164);
                  break;
               case 160:
                  if (curChar == 62 && kind > 27)
                     kind = 27;
                  break;
               case 163:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 167:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(168, 173);
                  break;
               case 168:
                  if ((0xa7ffff7e00000000L & l) != 0L)
                     jjCheckNAddTwoStates(168, 173);
                  break;
               case 169:
                  if (curChar == 62 && kind > 28)
                     kind = 28;
                  break;
               case 172:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 177:
                  if ((0xfffffffe00000000L & l) != 0L)
                     jjAddStates(37, 38);
                  break;
               case 178:
                  if (curChar == 62 && kind > 29)
                     kind = 29;
                  break;
               case 182:
                  if (curChar != 62)
                     break;
                  if (kind > 30)
                     kind = 30;
                  jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 183:
                  if ((0xfffffffe00000000L & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 188:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 190:
                  if ((0xa7ffff7e00000000L & l) != 0L)
                     jjAddStates(39, 40);
                  break;
               case 191:
                  if (curChar == 62 && kind > 31)
                     kind = 31;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x2ffffffeefffffffL & l) != 0L && kind > 32)
                     kind = 32;
                  break;
               case 3:
                  if ((0x7fffffec7ffffffL & l) != 0L)
                     jjAddStates(41, 42);
                  break;
               case 5:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 11:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 12:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar != 108)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 16:
                  if ((0x7ffffffefffffffeL & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 17:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 18:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 21:
                  if ((0x7ffffffefffffffeL & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 22:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 23:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 28:
                  if ((0x7fffffec7ffffffL & l) != 0L)
                     jjAddStates(43, 44);
                  break;
               case 30:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 36:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 37:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar != 100)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 41:
                  if ((0x7ffffffefffffffeL & l) != 0L && kind > 9)
                     kind = 9;
                  break;
               case 42:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 43:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 46:
                  if ((0x7ffffffeffffffffL & l) != 0L && kind > 10)
                     kind = 10;
                  break;
               case 47:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 48:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 49:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 52:
                  if (curChar == 107)
                     jjCheckNAddTwoStates(53, 54);
                  break;
               case 53:
                  if ((0x7fffffec7ffffffL & l) != 0L)
                     jjCheckNAddTwoStates(53, 54);
                  break;
               case 55:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 56:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 59:
                  if ((0x7fffffec7ffffffL & l) != 0L)
                     jjAddStates(45, 46);
                  break;
               case 61:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 64:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 67:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 68:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar != 121)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 72:
                  if ((0x7ffffffeffffffffL & l) != 0L && kind > 13)
                     kind = 13;
                  break;
               case 73:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 74:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 77:
                  if ((0x7ffffffeffffffffL & l) != 0L && kind > 14)
                     kind = 14;
                  break;
               case 78:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 79:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 84:
                  if ((0x7fffffec7ffffffL & l) != 0L)
                     jjAddStates(47, 48);
                  break;
               case 86:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 89:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 90:
                  if (curChar == 112)
                     jjCheckNAddTwoStates(91, 92);
                  break;
               case 91:
                  if ((0x7fffffec7ffffffL & l) != 0L)
                     jjCheckNAddTwoStates(91, 92);
                  break;
               case 94:
                  if ((0x7ffffffeffffffffL & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 95:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 97:
                  if (curChar == 110)
                     jjCheckNAddTwoStates(98, 105);
                  break;
               case 98:
                  if ((0x7ffffffeffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(98, 105);
                  break;
               case 100:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 106:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 107:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 103)
                     jjCheckNAddTwoStates(110, 111);
                  break;
               case 110:
                  if ((0x7fffffec7ffffffL & l) != 0L)
                     jjCheckNAddTwoStates(110, 111);
                  break;
               case 112:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 113:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 115:
                  if ((0x7fffffec7ffffffL & l) != 0L)
                     jjAddStates(49, 50);
                  break;
               case 117:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 122:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 123:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 118)
                     jjCheckNAddTwoStates(126, 127);
                  break;
               case 126:
                  if ((0x7fffffec7ffffffL & l) != 0L)
                     jjCheckNAddTwoStates(126, 127);
                  break;
               case 128:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 129:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 131:
                  if ((0x7ffffffeffffffffL & l) != 0L && kind > 22)
                     kind = 22;
                  break;
               case 132:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 133:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 136:
                  if (curChar != 101)
                     break;
                  if (kind > 23)
                     kind = 23;
                  jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 137:
                  if ((0x7ffffffeffffffffL & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 138:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 139:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 140:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 143:
                  if ((0x7ffffffeffffffffL & l) != 0L && kind > 24)
                     kind = 24;
                  break;
               case 144:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 145:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 150:
                  if (curChar != 114)
                     break;
                  if (kind > 25)
                     kind = 25;
                  jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 151:
                  if ((0x7ffffffeffffffffL & l) != 0L && kind > 25)
                     kind = 25;
                  break;
               case 152:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 154:
                  if ((0x7ffffffeffffffffL & l) != 0L && kind > 26)
                     kind = 26;
                  break;
               case 155:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 156:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 159:
                  if ((0x7fffffec7ffffffL & l) != 0L)
                     jjAddStates(51, 52);
                  break;
               case 161:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 162:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 165:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 166:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 168:
                  if ((0x7fffffec7ffffffL & l) != 0L)
                     jjAddStates(53, 54);
                  break;
               case 170:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 171:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 174:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 175:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if (curChar == 109)
                     jjCheckNAddTwoStates(177, 178);
                  break;
               case 177:
                  if ((0x7ffffffeffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(177, 178);
                  break;
               case 179:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 180:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 181:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 183:
                  if ((0x7ffffffeffffffffL & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 184:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 182;
                  break;
               case 185:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 186:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 187:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 189:
                  if (curChar == 116)
                     jjCheckNAddTwoStates(190, 191);
                  break;
               case 190:
                  if ((0x7fffffec7ffffffL & l) != 0L)
                     jjCheckNAddTwoStates(190, 191);
                  break;
               case 192:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 193:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 194:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 195:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 196 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   14, 19, 26, 39, 44, 51, 57, 70, 75, 82, 89, 90, 96, 108, 113, 124, 
   129, 135, 141, 149, 152, 157, 166, 175, 181, 188, 195, 53, 54, 91, 92, 98, 
   105, 110, 111, 126, 127, 177, 178, 190, 191, 3, 10, 28, 35, 59, 66, 84, 
   88, 115, 121, 159, 164, 168, 173, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x1ffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[196];
private final int[] jjstateSet = new int[392];
protected char curChar;
/** Constructor. */
public MyNewGrammarTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public MyNewGrammarTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 196; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
