/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package Test;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HTMLt = 5;
  /** RegularExpression Id. */
  int HTMLSTART = 6;
  /** RegularExpression Id. */
  int HTMLEND = 7;
  /** RegularExpression Id. */
  int HEADt = 8;
  /** RegularExpression Id. */
  int HEADSTART = 9;
  /** RegularExpression Id. */
  int HEADEND = 10;
  /** RegularExpression Id. */
  int LINKt = 11;
  /** RegularExpression Id. */
  int BODYt = 12;
  /** RegularExpression Id. */
  int BODYSTART = 13;
  /** RegularExpression Id. */
  int BODYEND = 14;
  /** RegularExpression Id. */
  int Pt = 15;
  /** RegularExpression Id. */
  int PSTART = 16;
  /** RegularExpression Id. */
  int PEND = 17;
  /** RegularExpression Id. */
  int SPANt = 18;
  /** RegularExpression Id. */
  int IMGt = 19;
  /** RegularExpression Id. */
  int DIVt = 20;
  /** RegularExpression Id. */
  int DIVSTART = 21;
  /** RegularExpression Id. */
  int DIVEND = 22;
  /** RegularExpression Id. */
  int TABLESTART = 23;
  /** RegularExpression Id. */
  int TABLEEND = 24;
  /** RegularExpression Id. */
  int TRSTART = 25;
  /** RegularExpression Id. */
  int TREND = 26;
  /** RegularExpression Id. */
  int THt = 27;
  /** RegularExpression Id. */
  int TDt = 28;
  /** RegularExpression Id. */
  int FORMSTART = 29;
  /** RegularExpression Id. */
  int FORMEND = 30;
  /** RegularExpression Id. */
  int INPUTt = 31;
  /** RegularExpression Id. */
  int IGNORE = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<HTMLt>",
    "<HTMLSTART>",
    "<HTMLEND>",
    "<HEADt>",
    "<HEADSTART>",
    "<HEADEND>",
    "<LINKt>",
    "<BODYt>",
    "<BODYSTART>",
    "<BODYEND>",
    "<Pt>",
    "<PSTART>",
    "<PEND>",
    "<SPANt>",
    "<IMGt>",
    "<DIVt>",
    "<DIVSTART>",
    "<DIVEND>",
    "<TABLESTART>",
    "<TABLEEND>",
    "<TRSTART>",
    "<TREND>",
    "<THt>",
    "<TDt>",
    "<FORMSTART>",
    "<FORMEND>",
    "<INPUTt>",
    "<IGNORE>",
  };

}
